### PR TITLE
Fix: no escape #\: and #\; not at beginning of line

### PR DESCRIPTION
**Pull request by myaosato**
Hello, t-sin.

I found a bag on indite function.

It add #\: to escape #\: and #\; not only at beginning of lines also in the middle of lines.

I fixed it to work only at beginning of lines.

If I misunderstand the specification, please tell me. 

Thank you.

### CODE REVIEW

**Comment by t-sin** [comment]
Oh yes, it's a bug! Thank you for finding and fixing it. 

The fix looks good to me. I'll merge it.

# Reproduce example

`:` or `;` not at the head of line, are escaped. In specification, they should not be escaped.

```
CL-USER> (with-input-from-string (in ":title
::hogehoge :
:;fugafuga ;")
           (rosa:indite (rosa:peruse-as-plist in)))
":title
::hogehoge ::
:;fugafuga :;
"
```

**Comment by t-sin** [comment]
Now CI failed, but it is probably caused by SBCL version, not by this fix. Don't mind!

**Comment by myaosato** [comment]
Thank you for checking and merging and kindly words.

**Comment by t-sin** [comment]
@t-sin some more tests are needed.

**Pull request merged**
